apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pv2je5c33-python 
  janus-idp.io/tekton: pv2je5c33-python
  backstage.io/kubernetes-id: pv2je5c33-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pv2je5c33-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml